### ISSUE TITLE
Investigate how models are mis-classifying ROIs in dense experiments 

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#71]
Based on stakeholder discussion, we would like to be able to provide more interpretation for why the classifier is marking ROIs invalid that are valid according to previous segmentation.

Tasks:
- [ ] Choose one of the dense experiments and look for trends in what appear to be mis-classified ROIs
- [ ] Create interpretable explanations for why the model is making its decision (LIME, SHAP)

Acceptance criteria:
- [x] Present summary of findings, and how we might adjust features to better align classifications with domain expectations

**Comment by kschelonka** [comment]
I took a look at one example of dense cells. I think this is more of a suite2p issue than a classifier issue. Quite a few apparent cells were missed by segmentation altogether, and many of the ROIs that are on top of cells are not a very cell-like shape. I can understand why the classifier would misclassify these ROIs based on shape for almost every instance...

Here's an example (experiment_id = 912791341). Labeled as cell = yellow, labeled as not cell = purple. 
![image.png](https://images.zenhubusercontent.com/5d8d3df983bdab000177f354/3c83c202-a790-4180-b5e3-983ae33163d8)

Compared to Marina's plot:
![image.png](https://images.zenhubusercontent.com/5d8d3df983bdab000177f354/ace6ce68-bcac-4113-bd70-1d476fcbdd0f)

When the ROIs are labeled by number, you can see that there are a few that definitely should have been merged. In Marina's plot the ROIs look a little better (and so it's more confusing why the classifier would misclassify) because you can't tell that they are actually two separate ROIs. When looking at these data qualitatively I think it will be important moving forward to visually distinguish separate ROIs in some way.
